### ISSUE TITLE
Error installing generator

### ISSUE THREAD

**Issue by geerzo** [yeoman/generator-karma#71]
I can't seem to get npm to install the generator. I keep getting the following error.

```
npm ERR! argv "node" "/Users/geerzo/.node/bin/npm" "install" "-g" "generator-angular"
npm ERR! node v0.10.35
npm ERR! npm  v2.2.0
npm ERR! path /Users/geerzo/.node/lib/node_modules/generator-karma/node_modules/yeoman-generator/node_modules/download/node_modules/fs-extra/node_modules/ncp/package.json
npm ERR! code ENOENT
npm ERR! errno 34
```

In digging further it seems as if it's ultimately caused when trying to install this package fs-extra@0.11.1 which is used by generator-karma >= 0.8.0. Newer versions of fs-extra seem to install (or older versions of generator-karma).

**Comment by eddiemonge** [comment]
Does this happen repeatedly? Or was it a one time occurrence? What if you try `npm i generator-karma` in a local file (without the `-g` flag)

**Comment by eddiemonge** [comment]
I can't seem to reproduce this. It might be a (temporary) npm issue.

**Comment by geerzo** [comment]
It is completely repeatable on my system. This is what I get running generator-karma locally

```
local test ruby-1.9.3-p547@p141  $ npm i generator-karma
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/Users/geerzo/.node/bin/npm" "i" "generator-karma"
npm ERR! node v0.10.35
npm ERR! npm  v2.2.0
npm ERR! path /private/tmp/test/node_modules/generator-karma/node_modules/yeoman-generator/node_modules/download/node_modules/fs-extra/node_modules/ncp/package.json
npm ERR! code ENOENT
npm ERR! errno 34

npm ERR! enoent ENOENT, open '/private/tmp/test/node_modules/generator-karma/node_modules/yeoman-generator/node_modules/download/node_modules/fs-extra/node_modules/ncp/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/test/npm-debug.log
```

**Comment by eddiemonge** [comment]
what if you try `npm cache clean` first?

**Comment by geerzo** [comment]
Cleaning out some stuff I was finally able to get it to work. What's odd is it was a fresh install of npm so not sure why the cache was bad.
