### ISSUE TITLE
Add option to support multiple frameworks

### ISSUE THREAD

**Issue by tomwayson** [yeoman/generator-karma#72]
I see that this [has been asked for before](https://github.com/yeoman/generator-karma/issues/66), and it seems relatively simple. I'm glad to make a PR, but wanted to validate my thinking first.

1) option: `--other-frameworks=requirejs,sinon` (is this a good name for the option?)
2) Update [this line](https://github.com/yeoman/generator-karma/blob/df00c317bfd6bd1d848fc2c32e969129b4fec741/templates/karma.conf.js#L17) (and corresponding line in coffee template) to something like: 
```
    // testing framework to use (jasmine/mocha/qunit/...)
    // and any additional frameworks in use (if any)
    frameworks: ['<%= options["test-framework"] %>' <%if (options["other-frameworks"]) { %>, <%= templateArray(options["other-frameworks"]]) %><% }%>],
```
3) Update [test](https://github.com/yeoman/generator-karma/blob/df00c317bfd6bd1d848fc2c32e969129b4fec741/test/test-options.js#L37) accordingly

Anything I'm missing?

**Comment by SBoudrias** [comment]
That plan looks good! PR welcomed!

**Comment by eddiemonge** [comment]
you could change test-framework to accept an array or a string so it stays backwards compatible. Maybe even a csv string and check for commas or use the value

**Comment by SBoudrias** [comment]
I wouldn't stress about backward compatibility, it's a fairly simple change to make in existing generators.
