### ISSUE TITLE
Drop CoffeeScript in favor of ES6 (Babel)

### ISSUE THREAD

**Issue by silvenon** [yeoman/generator-karma#78]
Ref. https://github.com/yeoman/generator-webapp/pull/543#issuecomment-111724489.

**Comment by arthurvr** [comment]
Yes please!

**Comment by sindresorhus** [comment]
:+1:

**Comment by arthurvr** [comment]
We should totally get rid of CoffeeScript :+1:.

Though looking at the actual [config file](https://github.com/yeoman/generator-karma/blob/master/templates/karma.conf.js) I don't see much value in having an ES6 specific version. People might as well just scaffold the ES5 version as it wouldn't really be much different.

**Comment by silvenon** [comment]
Sure, if ES6 doesn't make sense in this context, feel free to close.

**Comment by arthurvr** [comment]
> Sure, if ES6 doesn't make sense in this context, feel free to close

We should anyways get rid of CS right?

**Comment by silvenon** [comment]
Yes.

**Comment by eddiemonge** [comment]
We need a path for CS/TS/xx users going forward if we do drop these. At least a blog post or tutorial saying how they can still use those or advice on creating something to compose with this.

**Comment by eddiemonge** [comment]
See: https://github.com/yeoman/generator-karma/issues/83 
That issue is saying this one is resolved and its now actionable.
