### ISSUE TITLE
Error UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by ColoArg93** [yeoman/generator-karma#82]
Hello, i have a problem.
When i execute <code>npm install -g generator-karma</code> i have this error:

C:\WINDOWS\system32>npm install -g generator-karma
- dateformat node_modules\generator-karma\node_modules\yeoman-generator\node_modules\dateformat
- pretty-bytes node_modules\generator-karma\node_modules\yeoman-generator\node_modules\pretty-bytes
C:\Users\ivan\AppData\Roaming\npm
├── generator-karma@1.0.0
└── UNMET PEER DEPENDENCY yo@>=1.0.0

<code>
npm WARN EPEERINVALID generator-karma@1.0.0 requires a peer of yo@>=1.0.0 but none was installed.
</code>

I thought it would be solved updating Yeoman, but i've been updated Yeoman to the last version (1.5.0) and i continue having the same problem.

Can anyone help me, please?

**Comment by SBoudrias** [comment]
Thanks, that's fixed now :)
