### ISSUE TITLE
Deprecating CoffeeScript

### ISSUE THREAD

**Issue by eddiemonge** [yeoman/generator-karma#83]
Or rather removing it entirely as its easier than deprecating. 

Planning on a quick refactor to get this up to yo-gen 0.22.5, simplify some things in it, make it a bit more opinionated and various other fixes. At the same, it would be easier to remove CS support instead of having to maintain multiple code branches. The functionality should be able to be replaced with another generator that composes on top of this one.

Anyone opposed?

**Comment by SBoudrias** [comment]
LGTM :+1:

**Comment by sindresorhus** [comment]
:+1:

**Comment by eddiemonge** [comment]
Removing in v2. If people still want this, they can keep v1 (although it won't really be maintained anymore)
